<?php

use Illuminate\Database\Seeder;

class FigureTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('figure_types')->delete();

        \DB::table('figure_types')->insert([
            0 =>
                [
                    'id'          => 1,
                    'name'        => 'Mar',
                    'image'       => '/images/figure/apple.jpg',
                    'description' => '{"weight-loss":"<p>Silueta Dvs corespunde tipului constitutional &ldquo;<strong>MAR<\\/strong>&rdquo;, ce inseamna ca zona problematica a Dvs. este regiunea abdomenului. Dupa perioada de adaptare la efort fizic de <span style=\\"text-decoration: underline;\\">2-4 saptamini<\\/span> va recomandam sa faceti doua zile pe saptamana antrenamentul pentru muschii abdominali , si o data pe saptamana antrenamentul destinat tuturor grupelor de muschi, alternind cu antrenamentele pentru fese si coapse de la o saptamina la alta. Daca nu exista aceasta posibilitate continuati antrenamentele de trei ori pe saptamana frecventand toate antrenamentele dupa metoda<strong> Unica<\\/strong>, doar ca la fiecare complex de baza executati exercitii pentru abdomen. Apelati la ajuorul instructorului Dvs. pentru a fi ghidata in timpul antrenamentului. Va recomandam masaj pentru zona abdominala. Respectati regimul alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica si frecventati regulat antrenamentele pentru a ad\\u0103uga un plus de s\\u0103n\\u0103tate &icirc;n via\\u021ba Dvs. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul dorit.<\\/p>","maintenance":"<p>Silueta Dvs corespunde tipului constitutional &ldquo;<strong>MAR<\\/strong>&rdquo; \\u0219i ave\\u021bi o predispozi\\u021bie naturala de a depune mai u\\u0219or \\u0219i mai rapid \\u021besut adipos &icirc;n regiunea abdominal\\u0103. Va recoamandam sa va alimentati sanatos si echilibrat conform regimului alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii <strong>Unica<\\/strong>. Iar efortul fizic dozat dup\\u0103 Metoda Unica combinat cu procedurile de masaja v\\u0103 va ajuta s\\u0103 atinge\\u021bi scopul de a avea un abdomen tonifiat. Apela\\u021bi la ajutorul instructorului Dvs. pentru a v\\u0103 ghida pe parcursul antrenamentului!<\\/p>","weight-gain":"<p>Silueta Dvs. corespunde tipului constitutional &ldquo;<strong>M\\u0102R<\\/strong>&rdquo;, adic\\u0103 ave\\u021bi o predispozi\\u021bie natural\\u0103 spre a depune \\u021besut adipos mai u\\u0219or \\u0219i mai rapid &icirc;n zona abdominal\\u0103 \\u0219i mai greu cresteti masa musculare &icirc;n zona copaselor \\u0219i fesierilor. Este necesar regim anabolic destinat regiunii feselor \\u0219i coapselor pentru a dezvolta masa musculara propor\\u021bional \\u0219i corespunz\\u0103tor indicilor feminini. Apela\\u021bi la ajutorul instructorului pentru a v\\u0103 explica no\\u021biunile specifice \\u0219i a v\\u0103 oferi indica\\u021biile corespunz\\u0103toare regimului Dvs. Va recomandam efectuarea efortului fizic dozat dup\\u0103 metoda <strong>Unica<\\/strong> si respectarea regimului alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul de modelare armonioasa \\u0219i estetic\\u0103 a corpului.<\\/p>"}',
                ],
            1 =>
                [
                    'id'          => 2,
                    'name'        => 'Para',
                    'image'       => '/images/figure/pear.jpg',
                    'description' => '{"weight-loss":"<p>Silueta Dvs corespunde tipului constitutional &ldquo;<strong>PARA<\\/strong>&rdquo;, zona problematica fiind regiunea feselor si coapselor. Dupa perioada de adaptare la efort fizic de 2-4 saptamini va recomandam sa faceti doua zile pe saptamana antrenament pentru muschii coapsei si fesieri si o data pe saptamana antrenamentul destinat tuturor grupelor de muschi, alternind cu antrenamentele pentru muschii abdominali de la o saptamina la alta. Daca nu exista aceasta posibilitate continuati antrenamentele de trei ori pe saptamana frecventand toate programele doar ca la &ldquo;Complexul de baza&rdquo; executati exercitii pentru fesierei si coapse. Apelati la ajuorul instructorului Dvs. pentru a va ghida in timpul antrenamentului. Va recomandam masaj pentru zona fesierilor si a coapselor. Respectati regimul alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica si frecventati regulat antrenamentele pentru a ad\\u0103uga un plus de s\\u0103n\\u0103tate &icirc;n via\\u021ba dvs. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul dorit.<\\/p>","maintenance":"<p>Silueta Dvs corespunde tipului constitutional &ldquo;<strong>PAR\\u0102<\\/strong>&rdquo;, ceea ce &icirc;nseamn\\u0103 c\\u0103 acumula\\u021bi mai u\\u0219or \\u0219i mai rapid \\u021besut adipos &icirc;n regiunea fesierilor \\u0219i coapselor. Va recoamandam sa va alimentati sanatos si echilibrat conform regimului alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica. Iar efortul fizic dozat dup\\u0103 metoda Unica combinat cu procedurile de masaj v\\u0103 va ajuta s\\u0103 atinge\\u021bi scopul de a avea fesieri \\u0219i coapse tonifiate. Apela\\u021bi la ajutorul instructorului Dvs. pentru a v\\u0103 ghida pe parcursul antrenamentului.<\\/p>","weight-gain":"<p>Silueta Dvs corespunde tipului constitutional <strong>PAR\\u0102<\\/strong> ceea ce presupune ca veti adauga mai u\\u0219or \\u0219i mai rapid mas\\u0103 muscular\\u0103 &icirc;n regiunea feselor \\u0219i coapselor. Este necesar regim anabolic destinat regiunii feselor, coapselor, muschii bratelor si spatelui pentru a dezvolta masa musculara propor\\u021bional \\u0219i corespunz\\u0103tor indicilor feminini. Apela\\u021bi la ajutorul instructorului pentru a v\\u0103 explica no\\u021biunile specifice \\u0219i a v\\u0103 oferi indica\\u021biile corespunz\\u0103toare regimului Dvs. Respectati regimul alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul de modelare armonioasa \\u0219i estetic\\u0103 a corpului.<\\/p>"}',
                ],
            2 =>
                [
                    'id'          => 3,
                    'name'        => 'Clepsidra',
                    'image'       => '/images/figure/clepsidra.jpg',
                    'description' => '{"weight-loss":"<p>Silueta Dvs corespunde tipului constitutional &ldquo;<strong>CLEPSIDRA<\\/strong>&rdquo;. Surplusul de grasime se repartizeaza uniform pe tot corpul. Va recomandam sa frecventati antrenamentele dupa Metoda Unica de trei ori pe saptamana pentru a solicita toate grupele de muschi. Va recomandam sa efectuati masaj anticelulitic pentru a modela proportional silueta. Respectati regimul alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica si frecventati regulat antrenamentele pentru a ad\\u0103uga un plus de s\\u0103n\\u0103tate &icirc;n via\\u021ba Dvs. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul dorit.<\\/p>","maintenance":"<p>Silueta Dvs corespunde tipului constitutional <strong>CLEPSIDR\\u0102<\\/strong>, ceea ce \\u0103nseamn\\u0103 ca ave\\u021bi parametri corporali propor\\u021bionali. Va recoamandam sa va alimentati sanatos si echilibrat conform regimului alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica. Iar efortul fizic dozat dup\\u0103 metoda Unica combinat cu procedurile de masaj v\\u0103 va ajuta s\\u0103 atinge\\u021bi scopul de a avea corp tonifiat. Apela\\u021bi la ajutorul instructorului Dvs. pentru a v\\u0103 ghida pe parcursul antrenamentului.<\\/p>","weight-gain":"<p>Silueta Dvs corespunde tipului constitutional <strong>CLEPSIDR\\u0102<\\/strong>, ceea ce inseamna ca sunteti predispusa de a adauga masa musculara proportional. Efortul fizic dozat \\u0219i regulat dup\\u0103 metoda Unica v\\u0103 vajuta s\\u0103 atinge\\u021bi scopul de a creste masa musculara \\u0219i a modela estetic silueta. Apela\\u021bi la ajutorul instructorului pentru a v\\u0103 explica no\\u021biunile specifice \\u0219i a v\\u0103 oferi indica\\u021biile corespunz\\u0103toare regimului Dvs. Respectati regimul alimentar individual recomandat de c\\u0103tre nutri\\u021bioni\\u0219tii Unica. Aceste m\\u0103suri v\\u0103 vor ajuta s\\u0103 v\\u0103 atinge\\u021bi scopul dorit de modelare armonioasa \\u0219i estetic\\u0103 a corpului.<\\/p>"}',
                ],
        ]);
    }

}
